#!/bin/bash

source_dir=$(dirname $0)
kernel=$(uname)

for file in $(ls -a ${source_dir} | egrep '^\.[^.]+' | egrep -v '^\.git$'); do
    if [ "${file}" == ".slate" || "${file}" == ".Brewfile" ]; then
        if [ "${kernel}" != "Darwin" ]; then
            continue
        fi
    fi

    cp ${source_dir}/${file} ~/

done

echo "Dotfiles installed, enjoy."
