#!/bin/bash

source_dir=$(dirname $0)
kernel=$(uname)

for file in $(ls -a ${source_dir} | egrep '^\.[^.]+' | egrep -v '^\.git$'); do
    if [ "${file}" == ".slate" ] || [ "${file}" == ".Brewfile" ]; then
        if [ "${kernel}" != "Darwin" ]; then
            continue
        fi
    fi

    if [ "${file}" == ".gitconfig" ]; then
        echo "Enter git commit mail, followed by [ENTER];"
        read mail

        sed "s/%%PLACEHOLDER%%/${mail}/" ${source_dir}/${file} > ~/${file}
        continue
    fi

    cp ${source_dir}/${file} ~/

done

echo "Dotfiles installed, enjoy."
